import { Integration } from 'express-zod-api'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { env } from './config/env.js'
import { routes } from './routes.js'
import { getConfig } from './server.js'

const proxyTail = `

/* ===========================
   Proxy wrapper (hand-added)
   =========================== */

export const ez = new Client();

/**
 * Route-key proxy:
 *   api["get /v1/user/:id"]({ id: "123" })
 */
type Provide = typeof ez.provide;
type RouteKey = Parameters<Provide>[0];

export const api = new Proxy(
  {},
  {
    get(_target, prop) {
      if (typeof prop !== "string") return undefined;
      return (input: Parameters<Provide>[1]) =>
        ez.provide(prop as RouteKey, input as never);
    },
  },
) as {
  [K in RouteKey]: (input: Parameters<Provide>[1]) => ReturnType<Provide>;
};
`
const formatBuildStamp = (date: Date = new Date()): string =>
    new Intl.DateTimeFormat('en-US', {
        day: '2-digit',
        hour: 'numeric',
        hour12: true,
        minute: '2-digit',
        month: '2-digit',
        second: '2-digit',
        year: 'numeric', // AM/PM
    }).format(date)

const banner = `/**
 * ------------------------------------------------------
 * AUTO-GENERATED FILE — DO NOT EDIT.
 *
 * Generated by: express-zod-api on ${formatBuildStamp()} 
 * Build: ${new Date().toISOString()}
 * To regenerate: pnpm --filter @operator/api run gen:client
 * -------------------------------------------------------
 */
// @generated

`
async function main(): Promise<void> {
    const pkgFile = path.resolve(`${env.cwd}/package.json`)
    const outFile = path.resolve(`${env.cwd}/src/generated/api.ts`)
    ///load package (currently unused)
    //const banner = rollup.getBanner("gbtClient", pkg);
    const { default: pkg } = await import(pkgFile, { with: { type: 'json' } })

    const integration = await Integration.create({
        config: getConfig(),
        routing: routes,
        variant: 'client',
    })

    const clientCode = await integration.printFormatted()

    // Safety: if upstream changes and stops exporting Client, fail loudly.
    if (!/\bexport\s+(declare\s+)?class\s+Client\b/.test(clientCode)) {
        throw new Error(
            'Generated client does not export class Client. Cannot append proxy wrapper.',
        )
    }
    await mkdir(path.dirname(outFile), { recursive: true })
    await writeFile(outFile, `${banner}${clientCode}\n${proxyTail}`, 'utf8')

    console.log(`Generated combined client+proxy at: ${outFile}`)
}

main().catch((err: unknown) => {
    console.error(err)
    process.exit(1)
})
