// packages/operator-api-server/src/client/generator.ts
// Build-time script: generates the typed client and writes it to operator-api-client.
// Run via: pnpm gen:client

import { Integration } from 'express-zod-api'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { routes } from './../routes.js'
import { getConfig } from './../server.js'

const formatBuildStamp = (date: Date = new Date()): string =>
    new Intl.DateTimeFormat('en-US', {
        day: '2-digit',
        hour: 'numeric',
        hour12: true,
        minute: '2-digit',
        month: '2-digit',
        second: '2-digit',
        year: 'numeric',
    }).format(date)

const banner = `/**
 * ------------------------------------------------------
 * AUTO-GENERATED FILE — DO NOT EDIT.
 *
 * Generated by: express-zod-api on ${formatBuildStamp()}
 * Build: ${new Date().toISOString()}
 * 
 * To regenerate: pnpm --filter @operator/api-server gen:client
 * -------------------------------------------------------
 */
// @generated

`

async function main(): Promise<void> {
    // Output goes directly into operator-api-client
    const outFile = path.resolve(
        import.meta.dirname,
        '../../../operator-api-client/src/generated/api.ts',
    )

    const integration = await Integration.create({
        config: getConfig(),
        routing: routes,
        variant: 'client',
    })

    const clientCode = await integration.printFormatted()

    await mkdir(path.dirname(outFile), { recursive: true })
    await writeFile(outFile, `${banner}${clientCode}`, 'utf8')

    console.log(`Generated client at: ${outFile}`)
}

main().catch((err: unknown) => {
    console.error(err)
    process.exit(1)
})
